beautyhair/beautyhair/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('clients/', include('clients.urls')),
    path('orders/', include('orders.urls')),
    path('goods/', include('goods.urls')),
    path('store/', include('store.urls')),
    path('categories/', include('categories.urls')),
    path('reports/', include('reports.urls')),
    path('config/', include('siteconfig.urls')),
]

beautyhair/clients/urls.py
from django.urls import path
from .views import clients, new_client, view_client, edit_client

urlpatterns = [
    path('', clients, name='clients'),
    path('<int:pk>', view_client, name='view_client'),
    path('new/', new_client, name='new_client'),
    path('<int:pk>/edit/', edit_client, name='edit_client'),
]

beautyhair/goods/urls.py
from django.urls import path
from .views import get_goods

urlpatterns = [
    path('', get_goods, name='goods')
]

beautyhair/clients/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver


class Client(models.Model):
    GENDER =[
        ('m', 'Male'),
        ('f', 'Female'),
        ('u', 'Undefined')
    ]

    first_name = models.CharField(max_length=45, null=False, blank=False)
    last_name = models.CharField(max_length=45, null=False, blank=False)
    gender = models.CharField(max_length=1, choices=GENDER)
    registration_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'clients'


class Contact(models.Model):
    CONTACT_KINDS = [
        (0, 'phone'),
        (1, 'telegram'),
        (2, 'viber'),
        (3, 'whatsapp'),
        (4, 'instagram'),
        (5, 'facebook'),
    ]

    owner = models.ForeignKey(Client, on_delete=models.CASCADE)
    contact = models.CharField(max_length=160, null=False, blank=False, unique=True)
    kind = models.IntegerField(choices=CONTACT_KINDS, null=False, blank=False)
    primary = models.BooleanField(default=True, null=False)

    class Meta:
        db_table = 'contacts'


@receiver(pre_save, sender=Contact)
def ensure_single_primary_contact(sender, instance, **kwargs):
    if instance.primary:
        other_primary_contacts = Contact.objects.filter(owner=instance.owner, primary=True).exclude(pk=instance.pk)
        if other_primary_contacts.exists():
            other_primary_contacts.update(primary=False)

beautyhair/clients/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory

from .models import Client, Contact


class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['first_name', 'last_name', 'gender']
        widgets = {
            'gender': forms.Select()
        }


class AddContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['contact', 'kind', 'primary']
        widgets = {
            'contact': forms.TextInput(),
            'kind': forms.Select(),
            'primary': forms.RadioSelect(),
        }

    def clean(self):
        cleaned_data = super().clean()
        contact = cleaned_data.get('contact')
        if not contact:
            raise ValidationError('Contact not to be empty')
        return cleaned_data

ContactFormSet = inlineformset_factory(Client, Contact, form=AddContactForm, extra=1, can_delete=False)

beautyhair/clients/views.py
from django.shortcuts import render, redirect, get_object_or_404

from clients.forms import AddClientForm, ContactFormSet
from clients.models import Client, Contact


def new_client(request):
    if request.method == 'POST':
        form = AddClientForm(request.POST)
        contact_formset = ContactFormSet(request.POST, instance=Client())
        if form.is_valid() and contact_formset.is_valid():
            if not any(contact_form.cleaned_data.get('contact') for contact_form in contact_formset.forms):
                form.add_error(None, 'Contact not to be empty')
            else:
                client = Client.objects.create(
                    first_name=form.cleaned_data['first_name'],
                    last_name=form.cleaned_data['last_name'],
                    gender=form.cleaned_data['gender']
                )

                contact_formset.instance = client
                contact_formset.save()

            return redirect('view_client', pk=client.pk)
        else:
            return render(request, 'clients/client_form.html',
                          {'form': form, 'contact_formset': contact_formset, 'pk': None, 'create_mode': True})
    else:
        form = AddClientForm()
        contact_formset = ContactFormSet(instance=Client())

    return render(request, 'clients/client_form.html',
                  {'form': form, 'contact_formset': contact_formset, 'pk': None, 'create_mode': True})


def clients(request):
    all_clients = Client.objects.all()
    all_contacts = Contact.objects.all()
    context = {
        'clients': all_clients,
        'contacts': all_contacts,
        'title': 'Клиенты'
    }
    return render(request, 'clients/clients.html', context)


def view_client(request, pk):
    client = get_object_or_404(Client, pk=pk)
    contact = Contact.objects.filter(owner=pk)
    context = {
        'client_info': client,
        'contact_info': contact,
        'title': 'Клиент'
    }
    return render(request, 'clients/view_client.html', context)


def edit_client(request, pk):
    client = get_object_or_404(Client, pk=pk)
    contact = get_object_or_404(Client, pk=pk)
    if request.method == 'GET':
        context = {
            'form': AddClientForm(instance=client), 'pk': pk,
            'contact_formset': ContactFormSet(instance=contact)
        }
        return render(request, 'clients/client_form.html', context)

    elif request.method == 'POST':
        form = AddClientForm(request.POST, instance=client)
        contact_formset = ContactFormSet(request.POST, instance=contact)

        if form.is_valid() and contact_formset.is_valid():
            form.save()
            contact_formset.save()
            if 'delete' in request.POST:
                client.delete()
            return redirect('clients')

    return render(request, 'clients/client_form.html')

beautyhair/clients/templates/clients/client_form.html
{% extends "layout.html" %}

{% block content %}
  {% if create_mode %}
    <h2>New client</h2>
    <form action="{% url 'new_client' %}" method="post">
  {% else %}
    {% if add_contact_mode %}
      <h2>Add contact</h2>
      <form action="{% url 'add_contact' pk=pk %}" method="post">
    {% else %}
      <h2>Edit client</h2>
      <form action="{% url 'edit_client' pk=pk %}" method="post">
    {% endif %}
  {% endif %}
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p }}
    {{ contact_formset.as_p }}

    <button type="submit">Save</button>
    <button type="submit" name="delete" value="1" onclick="return confirmDelete()">Delete</button>

    <script>
      function confirmDelete() {
        return confirm("Are you sure you want to delete this client?");
      }
    </script>
  </form>

{% endblock %}

beautyhair/clients/templates/clients/clients.html
{% extends "layout.html" %}

{% block content %}

{% include 'clients/partials/actions.html' %}

<h1>{{ title }}</h1>

<hr/>
{% if clients %}
{% for client in clients %}
<ul>
    <li>
        <span>{{ client.first_name }} {{ client.last_name }}</span>
        <span><strong>{{ client.get_gender_display }}</strong></span>
    </li>
</ul>

<ul>
    {% for contact in contacts %}
    {% if contact.owner == client %}
    <li>
        <span>Контакт: {% if contact.primary %}<strong>{{ contact.contact }}</strong>{% else %}{{ contact.contact }}{% endif %}</span>
        <span>{{ contact.get_kind_display }}</span>
    </li>
    {% endif %}

    {% endfor %}
</ul>
<a href="{% url 'view_client' client.pk %}" class="menu-item">О клиенте</a>
<br/>

<hr/>

{% endfor %}

{% else %}
<p>Пока пусто =)</p>
{% endif %}

{% endblock %}

beautyhair/clients/templates/clients/view_client.html
{% extends "layout.html" %}

{% block content %}

{% include 'clients/partials/actions.html' %}

<h1>{{ title }}</h1>
<hr/>

<ul>
    <li>
        <span>{{ client_info.first_name }} {{ client_info.last_name }}</span>
        <span><strong>{{ client_info.gender }}</strong></span>
    </li>

    <li>
        <span>Дата регистрации: {{ client_info.registration_date|date:"d.m.Y" }}</span>
    </li>

    <ul>
        {% for contact_item in contact_info %}
        <li>
            <span>Контакт: {% if contact_item.primary %}<strong>{{ contact_item.contact }}</strong>{% else %}{{ contact_item.contact }}{% endif %}</span>
            <span>{{ contact_item.get_kind_display }}</span>
        </li>
        {% endfor %}
    </ul>

<div class="buttons-bottom">
    <a href="{% url 'edit_client' pk=client_info.pk %}" class="menu-item">
        <button type="button" class="edit-button">Редактировать</button>
    </a>
</div>

</ul>

{% endblock %}